server:
  port: 8005

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/toy_labs
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        open-in-view: false
        connection.provider_disables_autocommit: true

  sql:
    init:
      mode: always

#  data:
#    redis:
#      host: redis://localhost:6379
#      database: 0

logging:
  level:
    org.hibernate.type.descriptor.sql: info
    org.hibernate.orm.jdbc.bind: trace